name: Lab 7

# The pipeline should be triggered only on push to a "test" branch
on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # Run backend tests in the pipeline
      - name: Run backend tests
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
        run: ./gradlew test

      # Run the Jacoco report in the pipeline
      - name: Generate JaCoCo coverage report
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
        run: ./gradlew jacocoTestReport

      # Upload JaCoCo report as artifact
      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
